# Generated by Django 4.1.1 on 2023-01-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moviel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(max_length=100)),
                ('Budget', models.IntegerField()),
                ('IMDBrating', models.IntegerField()),
                ('Movieinfo', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='Movielist/images')),
            ],
        ),
    ]
